### PR TITLE
REST traverser ++api++

### PR DESCRIPTION
**Pull request by jensens**
See discussion in #87 and #73 and in https://github.com/plone/plone.rest/blob/rest-traverser/README.rst#content-negotiation

### CODE REVIEW

**Comment by tisto** [comment]
@jenkins-plone-org please run jobs

**Comment by sneridagh** [comment]
@jensens I would like to resurrect this, if possible, and even make a release to be able to test how it would look like. I played with tit a little this weekend, and it is promising. As you know we are working in the seamless/zero config mode, but it proved that it has some flaws that we need to overcome, and we think that this might come handy in order to fix them and make Volto play well with it. Probably one of the things will be to forget the "duality" of URLs using the content negotiation., but the other premises are still relevant, and we want them to still make them a reality.

The goal of seamless mode was to achieve Zero configuration (avoiding at the same time hardcoded API_PATH or other vars in code) with good sensible defaults when setting up deployments. So the seamless mode (+ zero config builds) wanted to solve this problems:

- API is "public", that means that you should expose the classic UI out there.
- The API returns you paths that does not correspond to the original (the object) that you are interacting with, so you have to adjust them (via a code helper) in every single call.
- Hard docker builds, since all the builds rely on build-time vars

and it has this pros:

- The zero config and the lack of having to rely on hardcoded variable names in the build
- Theoretically, you could deploy several sites using the same Volto SSR server without recompiling (just using the Host header in the reverse proxy)
- Opens the door for http://servername/sitename deployments as well, so several sites hosted the same Volto SSR server, we could use headers (same as Pyramid) to accomplish that as well.
- All internal links are app ones, so a link to a page /my-page will be returned by the API as is. So flattenToAppURL will still be required (for old deployments) but if seamless is adopted, it won't be required anymore in mid-term.
- The Plone classic UI is not public (which in some points clients might find it ugly and problematic from the SEO point of view), with the bonus that the indexers cannot reach them.
- Repeateable docker builds (since the config will be based on runtime) 

@ericof and I have questions:

- So, the change is not breaking, right? so it will be "over" the existing one. 
- What about images and files? How do we get them? (classic will be hidden)
- How would the nginx reverse proxy look like?

@ericof and me are open to discuss this, we can meet and talk about it, anytime.

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by tisto** [comment]
Test failure on Jenkins seems unrelated: https://jenkins.plone.org/job/pull-request-5.2-3.8/224/testReport/junit/plone.i18n.normalizer/ja/Normalizer/

@jenkins-plone-org please run jobs

**Comment by tisto** [comment]
@sneridagh @ericof CI is green. Please add your review. I can merge and release afterward.

**Review by ericof — APPROVED** [review]
LGTM!

**Comment by tisto** [comment]
@sneridagh @ericof @jensens released with 2.0.0a1: https://pypi.org/project/plone.rest/2.0.0a1/

**Pull request merged**
