### PR TITLE
Pre commit tisto

### PR DESCRIPTION
**Pull request by tisto**

### CODE REVIEW

**Comment by tisto** [comment]
@gforcada to gain a better understanding of our new coredev best practices I tried to re-create your PR on plone.rest going in small steps. Would you mind having a look?

**Comment by tisto** [comment]
@jenkins-plone-org please run jobs

**Review by davisagli — APPROVED** [review]
LGTM

**Comment by davisagli** [comment]
@tisto This PR is missing a towncrier entry, and it seems the repo is missing a check for that.

**Pull request merged**
