### PR TITLE
test(deprecation): Fix all warnings from our code

### PR DESCRIPTION
**Pull request by rpatterson**
Resolve all the deprecation warnings that originate in this package's code that are
exposed by running the tests.

### CODE REVIEW

**Comment by rpatterson** [comment]
For [the failing Python 2.7 CI checks](https://github.com/plone/plone.rest/runs/4634764047?check_suite_focus=true#step:9:1194), the errors I'm seeing seem to be related to type annotations in external libraries and I don't see how they could be related to my changes.  Will someone else please look at them and advise?

**Comment by rpatterson** [comment]
@jenkins-plone-org please run jobs

**Comment by tisto** [comment]
@rpatterson thanks for working on this! Seems that the failure is indeed unrelated to this PR. Though, we still have to fix it before we can merge this PR.

**Comment by rpatterson** [comment]
> @rpatterson thanks for working on this! Seems that the failure is indeed unrelated to this PR. Though, we still have to fix it before we can merge this PR.

Ok.  So if unrelated failures are blocking contributions, should I assume you'll be reaching out to those best suited to tackle these failures?  Or were you imagining that I need to get up to speed on the internals of this project's CI in order to fix this myself?  The latter sure seems like stacking things out of order.  OTOH, I'm getting pretty sick of all these CI false negatives and other unrelated impediments and I might appreciate being empowered to address them if @alecghica approves.

IMO, every CI false negative, false positive, etc. should be considered a red alert and top priority.

**Comment by tisto** [comment]
@rpatterson the CI fails because the buildout is broken. There is no magic involved. We are supporting ancient Plone versions that use outdated Python versions and we have to pay the price for it.

I fixed the issue:

https://github.com/plone/plone.rest/pull/129

Pls rebase with master and the build should be green.

**Comment by rpatterson** [comment]
> I fixed the issue:

Ah, so *your* the one that will tackle it.  ;-)  Thanks!

> Pls rebase with master and the build should be green.

Done.

**Comment by rpatterson** [comment]
The version compatibility failures in CI now are related to my changes.  Working on those now.

**Comment by rpatterson** [comment]
@jenkins-plone-org please run jobs

**Comment by rpatterson** [comment]
K, everything passing and ready for review, @tisto!

**Review by tisto — APPROVED** [review]

**Pull request merged**
