### PR TITLE
API methods can return a filestream_iterator for efficient streaming

### PR DESCRIPTION
**Pull request by zopyx**
of binary data as part of an API call

### CODE REVIEW

**Comment by zopyx** [comment]
see https://github.com/plone/plone.rest/issues/25

**Comment by tisto** [comment]
Thanks @zopyx! Would you mind writing a test for this?

**Comment by lukasgraf** [comment]
From my point of view I'd say generally :+1: for supporting the file stream iterator protocol (or rather, avoid breaking it's use).

A couple points though:
- No tests yet
- I'd consider using `IStreamIterator.providedBy(result)` instead of a type check
- This requires that the API developer sets an appropriate `Content-Type` themselves, otherwise we're sending a binary response body with `application/json`. Should there maybe also be a check that we only do this if the content-type has been set by the developer (is different from `application/json`)?

**Comment by tisto** [comment]
+1 for IStreamIterator check. We have to make sure that we get the HTTP content negotiation right. We can not return 'application/octet-stream' if the client asked for 'application/json'. I think plone.rest should include convenience functionality like this. I know this is more work right now, but maybe we should think about how to make the content negotiation more flexible.

**Comment by zopyx** [comment]
Check for IStreamIterator added.

THe documentation of an API method returning binary data should document the response content-type header and in such a case a client would send this header with Accept: 
Return a different response content-type header than one defined in the Accept: request should lead to an error.

**Comment by lukasgraf** [comment]
I agree, the current content negotiation doesn't do a whole lot of negotiation.

One issue I see is this: Right now, we're using an `Accept` header with content type `application/json` as an indicator that such a request is an API request (and all the magic happens after that).

If a client can request arbitrary media types, how are we going to distinguish an API request that asks for a HTML representation with `Accept: text/html` from a regular web-browser without introducing a new HTTP header that we require API clients to set?

**Comment by zopyx** [comment]
"""
a client can request arbitrary media types, how are we going to distinguish an API request that asks for a HTML representation with Accept: text/html from a regular web-browser without introducing a new HTTP header that we require API clients to set?
"""

As designer and implementor of a REST API it is up to you what to implement.Right now the plone.rest(api) only supports JSON in, JSON out. My patch extends the functionality JSON, JSON + binary data out. A JSON method implementation (or its configuration) must decide or specify the output formats that it can handle. 

My code has a download API that would provides binary data as application/zip download.
How would plone.rest react for Accept: text/html  here? Would it be up to the negotiator to reject
the request or up to the method of ignore the Accept: header?

**Comment by zopyx** [comment]
Somehow the Travis builds seem to hang during the test phase.

**Comment by buchi** [comment]
IMHO this is the wrong place to add this kind of functionality. plone.rest is about providing the infrastructure for defining RESTful services (endpoints). Implementations of RESTful services are done in other packages, e.g. plone.restapi.

Right now, plone.rest is limited to requests containing an `Accept: application/json` header. In fact the accept header is used to distinguish between requests handled by plone.rest services and requests handled by default traversal. Defining services for other content types is desirable and plone.rest should provide this functionality in the future.

By returning `application/octet-stream` content type in response to an `application/json` request you're violating the recommendations of the HTTP protocol. Unfortunately there's currently no proper way to return an `application/octet-stream` content type with a plone.rest service.

For your use case, I recommend to override the `__call__()` method in your service implementation.

Support for other content types in addition to `application/json` in plone.rest should be added in the future.

**Comment by zopyx** [comment]
On 13 Dec 2015, at 19:55, Thomas Buchberger wrote:

> IMHO this is the wrong place to add this kind of functionality. plone.rest is about providing the infrastructure for defining RESTful services (endpoints). Implementations of RESTful services are done in other packages, e.g. plone.restapi.

It is exactly the right place. Where is defined that a REST API should work with JSON-in, JSON-out...REST does not say anything
about formats IMO.
>
> Right now, plone.rest is limited to requests containing an `Accept: application/json` header. In fact the accept header is used to distinguish between requests handled by plone.rest services and requests handled by default traversal. Defining services for other content types is desirable and plone.rest should provide this functionality in the future.

see above...independent of restrictions or implementation details: a REST API should be able to deal with binary data (in and out) in an efficient way.

>
> By returning `application/octet-stream` content type in response to an `application/json` request you're violating the recommendations of the HTTP protocol.

Reference?

> Unfortunately there's currently no proper way to return an `application/octet-stream` content type with a plone.rest service.

There is - see my PR.

>
> For your use case, I recommend to override the `__call__()` method in your service implementation.

I disagree. 

API methods should be bound to 
- request method
- optional endpoint
- incoming mime-type (default to app/json)
- optional outgoing mime-type(s) (default to app/json)

The current assumption of JSON-in JSON-out is very limited (sufficient perhaps to plone.restapi) but not sufficient
enough in order to implement and support more complicated REST API (as I am trying to do right now).
REST APIs in my opinion should support more than only JSON-in JSON-out. 


>
> Support for other content types in addition to `application/json` in plone.rest should be added in the future.

This is not about content-types, this is about content negotiation and a discussion about what plone.rest really stands
for.

**Comment by buchi** [comment]
> It is exactly the right place...

I agree, REST APIs are not limited to JSON. But plone.rest is *not* an implementation of a REST API. The implementation is done in plone.restapi. plone.rest only provides the service directive for defining and implementing REST endpoints.

> ... a REST API should be able to deal with binary data (in and out) in an efficient way.

No objections. However this shouldn't be solved in a generic manner in plone.rest but should be handled in concrete implementations like plone.restapi. There may be situations where returning binary data in JSON is intended even if it's inefficient. As already said, the API implementation and not plone.rest should be responsible for dealing with input and output data.

> Reference?

See [RFC 2616 section 14.1](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html)  "If an Accept header field is present, and if the server cannot send a response which is acceptable according to the combined Accept field value, then the server SHOULD send a 406 (not acceptable) response."

> There is - see my PR.

I do not consider this a *proper* way. In general a client requesting a resource with an accept header of `application/json` is expecting a response of content type `application/json` containing JSON. 

> API methods should be bound to...

I agree, but right now plone.rest is missing this functionality. While plone.rest should support content negotiation it can impossibly support all possible representations. Representations of a resource are subject to an API implementation like plone.restapi. 

Currently plone.rest includes some JSON serialization functionality. This is mainly because of historical reasons I guess. If plone.rest is going to support other response media types all JSON serialization functionality should be moved to plone.restapi.

That's my main point: plone.rest provides a way to implement representations of a resource but it does not implement it.

**Comment by buchi** [comment]
Closing this as it doesn't fit here. plone.rest no longer handles rendering of responses. see also #52

**Pull request closed without merging**
